[package]
name = "matter-ecs/plasma"
description = "A declarative, immediate mode UI widget library for Roblox"
version = "0.4.4"
license = "MIT"
authors = [
    "Eryn L. K.",
    "Lucas Gangstad <lucas@lasttalon.dev>",
    "Ukendio <ukendio@gmail.com>",
]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = [
    "example",
    "docs",
    "Packages",
    ".moonwave",
    "build",
    "pages",
    "tests",
    "stories",
    "plasma.rbxm",
    "roblox.toml",
]

[dev-dependencies]
TestEZ = "roblox/testez@0.4.1"
